#   - Open your Docker Desktop App > Preferences > Resources > Advanced > Increase the memory allocated
---
version: '3'
 
 
services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    container_name: spoilers-postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DATABASE=postgres
      - POSTGRES_WAL_LEVEL=logical
    ports: 
      - "5432:5432"
 
  tensorflow-serving:
    image: tensorflow/serving
    ports: 
      - "8501:8501" 
    volumes: 
      - "./models:/models/spoiler_filter_api"
    environment: 
      - MODEL_NAME=spoiler_filter_api